---
name: PartiesPlugin
author: bitrule
version: "1.0"
api: 5.0.0
main: bitrule\parties\PartiesPlugin
permissions:
  parties.command.party:
    default: true
    description: Allows the player to use the /party command
...
